### PR TITLE
More robust typing & Fix for some tsconfig strict type issues

### PR DESCRIPTION
**Pull request by Dudeonyx**
This PR hopefully fixes issues that pop up when strict is set to true in tsconfig and should make the typing more robust in general.
Though I tried to cover as many edge cases as possible further testing is recommended.

These are the some of the more obvious issues fixed.

Fix no. 1 error when using tw on a Component without a className prop.

```ts
const Component = (props:{ others: string}) => <div {...props} />

const StyledComponent = tw(Component)`` // gives type error
```

Fix no. 2 Optional props added using utility types get stripped out.

```ts
type WithChildren<P> = P & { children?: any } // utility type that adds optional children prop

const Component = (props: WithChildren<{ others: string}>) => <div {...props} />
// Component has prop type `{ others: string } & { children?: any }`

const StyledComponent = tw(Component)`text-white`
// StyledComponent has prop type { others: string }

const node = <StyledComponent>hello</StyledComponent> // gives type error as it has no `children` prop
```

### CODE REVIEW

**Review by Dudeonyx — COMMENTED** [review]
Renamed some functions & variables to be more explicit, especially `templateFunction` to `templateFunctionFactory` to avoid confusion with `TemplateFunction` type which it returns. Previously I would mistake that `templateFunction` is of type `TemplateFunction` when it instead returns functions of type `TemplateFunction`.

**Comment by MathiasGilson** [comment]
Damn @Dudeonyx! Amazing PR great work!

I just re-exported the interface `TailwindComponent` because it was necessary to export the library inside another one #38

**Comment by MathiasGilson** [comment]
@Dudeonyx the typing tests don't pass for me, could you have a look?

I get the error `Expression produces a union type that is too complex to represent.`

I tried to force publish but then my project would not build anymore so I reverted back to the 2.1.2.

**Comment by Dudeonyx** [comment]
@MathiasGilson Yeah, I had that bug as well, but I thought I had fixed it before making this PR.

It strange as it only happens when running yarn build, which then runs the tests then type tests.

Running yarn run test, which also runs the type tests does not give this error.

Anyway, I know the cause of the error, it's the type  `keyof JSX.IntrinsicElements`/`IntrinsicElementsKeys`. The union is too large consisting of 138 types. In certain scenarios typescript has to account for 138^n types which causes the error.

I have a fix that minimises use of this union, just need to make sure everything still works fine.

**Comment by MathiasGilson** [comment]
@Dudeonyx Cool!

Let me know once I can test again 😉

**Pull request merged**
